# Generated by Django 3.1.2 on 2021-10-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211004_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
    ]
